### ISSUE TITLE
Proof read vignette / high-level doc

### ISSUE THREAD

**Issue by adrian-lison** [epinowcast/epinowcast#215]
I noticed a few minor things in the vignettes / docs and would like to go through them once before the [0.2.1 release](https://github.com/orgs/epinowcast/projects/3/views/1) to check for clarity etc.

**Comment by seabbs** [comment]
How is this going 😄 - it would be great to aim for a release next week I think so we can get on to the more exciting work in `0.3.0`.

**Comment by parksw3** [comment]
Sam suggested that I can help with this. Which vignette should I look at? Both `germany-age-stratified-nowcasting.Rmd` and `model.Rmd`? What's the timeline?

**Comment by seabbs** [comment]
Just a reminder on this @parksw3 (and to look at the `develop` branch). No worries if you don't get to it.

**Comment by parksw3** [comment]
I think you said I can look at it over the weekend, right?

**Comment by seabbs** [comment]
yes of course! ❤️

**Comment by parksw3** [comment]
Some thoughts.

`model.Rmd`:

- (minor) Maybe worth writing out $n_{g,t,d}$ in terms of $p_{g,t,d}$?

- I think there needs to be some more clarification between the relationship between $N$, $\lambda$, and $n$ before you get to the default model. In particular, the definition $\lambda_{g,t} = E[N_{g,t}]$ makes it sound like the model is doing something like this:

$$
N_{g,t} \sim Distrib(\textrm{mean}=\lambda_{g, t})
$$

but at the end of the document, I learn that it's a bit more complicated than this.

- Likewise, this sentence is also confusing: "For each t and g these notifications are assumed to be drawn from a multinomial distribution with $N_{g,t}$ trials and a probability vector ($p_{g,t,d}$) of length D." because it doesn't look like you're actually doing this at the end? $n$ is drawn from a negative binomial distribution and then summed up to make $N$?

**Comment by parksw3** [comment]
`germany-age-stratified-nowcasting.Rmd`

- "reporting delays are fixed across age groups and time" Do you mean that the delay "distribution" is fixed? 

- I can't figure out where you're specifying the data when you're fitting the model here. Something missing? Need to be explained a bit more clearly. 

```r
fit <- enw_fit_opts(
  save_warmup = FALSE, output_loglik = TRUE, pp = TRUE,
  chains = 2, threads_per_chain = threads, 
  iter_sampling = 500, iter_warmup = 500,
  show_messages = FALSE, refresh = 0,
  adapt_delta = 0.98, max_treedepth = 15
)
nowcast <- epinowcast(pobs,
  fit = fit,
  model = multithread_model
)
```

- It looks like `data = pobs` argument is missing from the `multithread_model`?

- "To speed up model fitting we make use of posterior information from the previous model (with some inflation) for some parameters. Note that this is not a truly Bayesian approach and in some situations may be problematic." I think this is always problematic, right? You already have some sort of posterior from the data, and you're using the posterior to fit to the same data again (even though you're using the same model). So you're fitting to the same data twice right? I'm not saying you shouldn't do this but the limitation should be made clearer.

- Reference day of the week effect section. It looks like the original fit also captures the day of the week effect. So I'm a bit confused how the original model captures the day of  the week effect. Also not sure what the differences are between two fits (besides the fact that they're using different models). It looks like the fits are qualiatatively similar? Maybe something wrong with the first figure? The code shouldn't even run because you haven't specified the data yet...?

- Posterior predictions figure is impossible to read... need to zoom in to show a concrete example?

- "As noted using the posterior predictions from the simple model fit above there appears to be a day of the week effect for reported observations" this is really hard to tell... also need to explain the differences between the day of the week effect for reporting day vs reference day more clearly. I also wonder if it's easier to explain the reporting day effect first and reference day after? I feel like you meant to do this because the reference day of the week model is more complicated:

```
expectation_module <- enw_expectation(
  ~ 0 + (1 | day_of_week) + (1 | day:.group), data = pobs
)
```

than the reporting day of the week model:

```
report_module_dow <- enw_report(~ (1 | day_of_week), data = pobs)
```

I think it makes sense to introduce the more complicated model later?

**Comment by parksw3** [comment]
`README.Rmd`

- Probably a good idea to explain what is meant by day of reference vs report in this document too.

- What is `(1 | day)`? Is this the random walk?

- "Rather than using the methods supplied for epinowcast directly, package functions can also be used to extract nowcast posterior samples, summarise them, and then plot them" Is this sentence missing something? I'm confused what "package functions" are referring to. It sounds like you might be referring to a different package? Not sure why functions vs methods are different here...

- Am curious why there is a consistent underestimation. Would be useful to give some information (e.g., what things you can try, what to read) for readers who want to learn more (but don't have to show how to actually do more complicated things)...

**Comment by seabbs** [comment]
Thanks for this @parksw3 - really helpful stuff. Just digesting them and then need to think about what needs changing. Did you want to make any suggested changes yourself as a PR or shall I have a first pass and then tag you in?

**Comment by seabbs** [comment]
Quite a lot to unpack there so I have slit out into individual issues (that can then each be tackled in separate PRs maybe by different people).

**Comment by seabbs** [comment]
Is this safe to close in favour of the 3 new issues or are there other parts of the docs you wanted to check @adrian-lison?
