### ISSUE TITLE
Improving the workflow for README updating

### ISSUE THREAD

**Issue by pearsonca** [epinowcast/epinowcast#379]
The current CI triggers automatic building of README.md from README.Rmd when that file is updated.

This is desirable overall: one less thing to forget to do, and is highly automateable.

But it presents some downsides:
 - noticed in #375 that automation on partial complete PRs (because drafted in this case, but likely also during back and forth revisions) will trigger and build the README. This invalidates the git history on the developers local copy, which is a bit of an annoying surprise. The fix is straightforward enough (`git pull --rebase`) if you know what you're doing.
 - minor: I imagine people might miss that their changes lead to README.Rmd failing to knit

I think a more ideal version might be:
 - build-and-commit ONLY on merge to main -- however, apparently this presents problems for merge queuing?
 - convert the branch build to *not* commit changes (though still attempt to knit, report knit errors, etc)

A more minimal solution would simply be to collect the automation documentation, and note corrective actions like above for these kind of hiccups. I imagine there are a few other simple-fixes-if-you-know.

I'm not super familiar with what's possible on merge queue actions - is there a "when done with the queue, do clean up / automated commits" (versus doing them admidst the series)? That seems like a potential avenue to solve this - have building the README as the final step in any merge "queue" (including queues of 1).

**Comment by seabbs** [comment]
I think  I agree that updating the README in PRs can be invasive. I think the solution would be to: 

- Update the current CI to build the README if in a PR but not to update the PR with this new build (i.e and store it as a environment
- Ideally add a comment ability to tell contributors/reviews that this has been done and to link to the environment for easy download
- Ideally add the ability to dispatch README updates as a comment action so that reviews can see the latest updates
- Keep the current functionality so that the README will be updated on `main` when changes to `README.Rmd` are pushed. This does mean that whilst README.Rmd is being built `README.md` will be out of date. 

A question I have is how to handle stopping people pushing the updated README in their PRs (if this is something we no longer want). One option could be to add `README.md` to the `.gitignore` and then override this in the GitHub Action that renders the README?

**Comment by pearsonca** [comment]
Maybe something like using the [assume-unchanged](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-update-index.html#_using_8220_assume_unchanged_8221_bit) feature in git?

**Comment by Bisaloo** [comment]
> Keep the current functionality so that the README will be updated on `main` when changes to `README.Rmd` are pushed.

The somewhat annoying part here is that you need a token with extra permissions to do this on a protected branch such as `main`. From a security standpoint, this is not ideal. The situation may be slightly better now that we have fine-grained permission tokens though.

**Comment by seabbs** [comment]
`assume-unchanged` seems like a good idea but I don't know anything about it. 

Ah yeah @Bisaloo - good point. I think it could be worth it here though as it quite annoying PR noise!

**Comment by seabbs** [comment]
I'm now also wondering if it would be preferable to do this for `man` files as well to reduce PR noise. I've never seen that done before though so likely a little over the top.

**Comment by sbfnk** [comment]
And a regularly scheduled one for the precompiled vignettes? Perhaps ideally checking if they have changed since the last recompile.

**Comment by seabbs** [comment]
yes agree. For the lighter weight vignettes we could render them on `main` but probably not for chunkier ones unless we work out how to bring our own runner (which I think wouldn't be impossibly hard).

**Comment by seabbs** [comment]
I just had a look at it seems like self hosted runners are very much a no go due to security concerns.

**Comment by seabbs** [comment]
We now have everything being rendered by CI and merged via PR which I think is working nicely so closing.
