### ISSUE TITLE
Linking in docs broken

### ISSUE THREAD

**Issue by zsusswein** [epinowcast/epinowcast#448]
**Describe the bug**
I was looking for some information in the Getting Started vignette in the dev documentation. The link under "R Vignettes" to the "Getting Started" vignette is broken. There are also some broken links when trying to search for terms.

**To Reproduce**
1. Go to the homepage
2. Click on "Get started nowcasting"

**Expected behavior**
A link to[ this page](https://package.epinowcast.org/dev/articles/epinowcast.html)

**Comment by seabbs** [comment]
Hi @zsusswein, 

Thanks for reporting - this seems like it must be frustrating. 

The problem here is we have a dev version and a release version. The README is pointing at the release version but we don't actually have the vignette it points to in that version yet (i.e this one https://package.epinowcast.org/dev/articles/epinowcast.html).

We are currently planning a release which will fix this or we could resolve it now by explicitly fixing the README. That might be more work that its worth though as we would then need to change it back!
